// Fills the "Club Stats" panel from public/stats.json (generated by scrape_ebird.py).
import { esc } from './outings.js';

const fmt = (n) => Number(n || 0).toLocaleString('en-US');

function sinceLabel(iso) {
  const date = new Date(`${iso}T12:00:00`);
  return isNaN(date) ? '' : date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
}

function tile(icon, value, label) {
  return `
    <div class="stat-tile">
      <div class="stat-value"><span class="stat-icon" aria-hidden="true">${icon}</span>${fmt(value)}</div>
      <div class="stat-label">${esc(label)}</div>
    </div>`;
}

function render(stats) {
  const grid = document.getElementById('stats-grid');
  const since = document.getElementById('stats-since');
  if (!grid) return;

  if (since && stats.since) since.textContent = `Hancock County, Maine · since ${sinceLabel(stats.since)}`;

  grid.innerHTML = [
    tile('🐦', stats.species, 'Species Observed'),
    tile('🔢', stats.individuals, 'Individual Birds Counted'),
    tile('📋', stats.checklists, 'eBird Checklists'),
    tile('🥾', stats.outings, 'Outings'),
    tile('⏱️', stats.hoursInField, 'Hours in the Field'),
    tile('📍', stats.locations, 'Locations Visited'),
  ].join('');

  const footnote = document.getElementById('stats-footnote');
  if (footnote) {
    footnote.textContent = `Pulled from our eBird trip reports · updated ${stats.generated}`;
  }
}

async function loadStats() {
  const grid = document.getElementById('stats-grid');
  if (!grid) return;
  try {
    const response = await fetch('/stats.json');
    if (!response.ok) throw new Error('Failed to fetch stats');
    render(await response.json());
  } catch (error) {
    console.error('Stats loading error:', error);
    grid.innerHTML = '<p class="stats-empty">Stats are on their way — check back soon.</p>';
  }
}

document.addEventListener('DOMContentLoaded', loadStats);
